# ワークフロー名
name: GitHub-Instapy-Auto

# 発火タイミング
on:
  schedule:
    - cron: '45 14 * * *'
    - cron: '55 15 * * *'
    
jobs:
  build:
    # windowsの最新版環境内で処理
    runs-on: windows-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install instapy
      - name: Run script
        env:
          CHANNEL_ACCESS_TOKEN: "YOUR_CHANNEL_ACCESS_TOKEN"
          USER_ID: "YOUR_USER_ID"
        run: |
          # instagram_bot_ver4.pyの実行
          python instagram_bot_ver4.py
